[build]
publish = "_site"
command = "npm run build"

[functions]
directory = "netlify/functions/"

[[redirects]]
from = "/preview/:slug/"
to = "/.netlify/functions/preview"
status = 200
force = true
_generated_by_eleventy_serverless = "preview"

[[redirects]]
from = "/:slug/preview/"
to = "/.netlify/functions/serverless"
status = 200
force = true
_generated_by_eleventy_serverless = "serverless"
